apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-service
  namespace: qa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-service
  template:
    metadata:
      labels:
        app: mock-service
    spec:
      containers:
        - name: mock-service
          image: ghcr.io/belf-kr/mock-service/nestjs
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mock-service
  namespace: qa
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: mock-service
