@Host = http://localhost:3002
@Router = todo-service

### 오늘 하루 todo list 조회
GET {{Host}}/{{Router}}/today-todos

### 잔디밭 조회
GET {{Host}}/{{Router}}/glass

### 잔디밭 조회
GET {{Host}}/{{Router}}/get-all-colors